<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageLicenseUrl>http://jamie-davis.github.io/ConsoleTools/LICENSE</PackageLicenseUrl>
    <PackageProjectUrl>http://jamie-davis.github.io/ConsoleTools/</PackageProjectUrl>
    <PackageTags>Console Toolkit .NET</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSource>True</IncludeSource>
    <IncludeSymbols>True</IncludeSymbols>
    <Description>Build command line applications quickly and easily. Simple to learn and gets out of your way fast, let the toolkit handle the command line parameters, the output formatting, capturing user input and more.</Description>
    <Version>2.0.1</Version>
    <Authors>Jamie Davis</Authors>
    <Product>Console Toolkit</Product>
    <Copyright>Jamie Davis 2014-2025</Copyright>
    <PackageReleaseNotes>Fixed potential deadlock.</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0" />
  </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="ConsoleToolkitTests" />
    </ItemGroup>
</Project>