using System.Collections.Generic;
using VT100.FullScreen.ScreenLayers;

namespace VT100.FullScreen.ScreenLayers
{
    internal static class BoxRenderer
    {
        internal static void RenderToPlate(IEnumerable<BoxRegion> regions, Plate plate)
        {
            var map = BoxMapMaker.Map(regions);
        }
    }

    internal static class BoxMapMaker
    {
        internal BoxMap Map(IEnumerable<BoxRegion> regions)
        {
            var boxCharacters = new BoxCharRequest[plate.Height * plate.Width];
            foreach (var boxRegion in regions)
            {
                
            }

            return new BoxMap(boxCharacters);
        }
    }

    /// <summary>
    /// Immutable class containing a box map generated by <see cref="BoxMapMaker"/>
    /// </summary>
    internal class BoxMap
    {
        public BoxCharRequest[] BoxCharacters { get; }

        public BoxMap(BoxCharRequest[] boxCharacters)
        {
            BoxCharacters = boxCharacters;
        }
    }
}